spring:
  application:
<<<<<<< HEAD
    name: tiny-url-gateway
=======
    name: srd-gateway
>>>>>>> d46c3e4f23b5d4e99a1f33ed5f995ce06241393d
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
        registerHealthCheck: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
<<<<<<< HEAD
        - id: tiny-url
          uri: lb://tiny-url-backend
          predicates:
            - Path=/short-url/**, /url/**
=======
        - id: srd
          uri: lb://srd-greeter
          predicates:
            - Path=/greet/**
>>>>>>> d46c3e4f23b5d4e99a1f33ed5f995ce06241393d
          metadata:
            response-timeout: 500
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT,INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,DELETE
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

server:
  port: 8080
